version: 2
jobs:
  checkout:
    docker: &docker
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache: &restore_cache
          name: Restore go modules cache
          keys:
            - mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
      - run: &vendoring
          name: Vendoring
          command: go mod download
      - save_cache: &save_cache
          name: Save go modules cache
          key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
  test:
    docker: *docker
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *vendoring
      - save_cache: *save_cache
      - run: go get -u github.com/modocache/gover
      - run: go get -u golang.org/x/lint/golint
      - run: go get -u github.com/axw/gocov/gocov
      - run: go get -u github.com/mattn/goveralls
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      # Setup dep
      - run: go vet ./...
      - run: go test -race -test.v ./...
      - run: go test -race -cover -v -coverprofile=./iceflake.coverprofile github.com/istyle-inc/iceflake
      - run: go test -race -cover -v -coverprofile=./client.coverprofile github.com/istyle-inc/iceflake/client/iceflake
      - run: go test -race -cover -v -coverprofile=./app.coverprofile github.com/istyle-inc/iceflake/app
      - run: gover
      - run: goveralls -coverprofile=./gover.coverprofile -service=circle-ci -repotoken=$COVERALLS_TOKEN

  build:
    docker: *docker
    working_directory: /go/src/github.com/istyle-inc/iceflake
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *vendoring
      - save_cache: *save_cache
      - run: go get -u github.com/goreleaser/goreleaser
      - run: goreleaser --rm-dist

workflows:
  version: 2
  without_release:
    jobs:
      - test:
          filters:
            tags:
              ignore: /^v.*/
  with_release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
